"""
MCP server exposing local Markdown documentation via LlamaIndex.

This server uses the LlamaIndex library to build a persistent vector store
from a directory of Markdown files.  It exposes two tools to the Model
Context Protocol (MCP) client:

  1. ``search_docs(query: str, k: int = 6) -> list[{path, heading, score, snippet}]``
     Perform a similarity search over the indexed Markdown chunks and return
     up to ``k`` results.  Each result contains the relative path to the
     source file, the best available heading context, the similarity score,
     and a short excerpt from the matched section.

  2. ``ask_docs(question: str) -> {answer: str, citations: list[{path, heading, snippet}]}``
     Generate an answer to a natural‑language question using a retrieval‑augmented
     generation approach.  The answer is grounded in the indexed content.
     Citations are returned for each supporting chunk.

The server reads configuration from environment variables.  In particular,
``DOCS_DIR`` points to the directory containing your Markdown files and
defaults to ``./docs``.  If the directory does not exist or contains no
Markdown files, the server will exit with a non‑zero status at start up.

OpenAI credentials are loaded from the environment as well; see
``README.md`` for details on which variables must be defined.
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from mcp.server.fastmcp import FastMCP

try:
    # Core LlamaIndex imports.  These are imported lazily to avoid
    # incurring import overhead or hard failures before we verify the docs
    # directory exists.  If a required submodule is missing, an ImportError
    # will be raised here rather than at runtime in tool functions.
    from llama_index.core import Document, StorageContext, VectorStoreIndex, load_index_from_storage
    from llama_index.core.node_parser import MarkdownNodeParser
    from llama_index.core.service_context import ServiceContext
    from llama_index.embeddings.openai import OpenAIEmbedding
    from llama_index.llms.openai import OpenAI
except ImportError as exc:
    # Provide a clear error message if dependencies are missing.  This makes
    # it obvious during server startup which package is not installed.
    missing = str(exc).split(" '" )[-1].split("'")[0]
    raise SystemExit(
        f"Missing dependency: {missing}. Please install required packages as described in the README."
    )

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Names of the OpenAI models to use.  Update these constants to swap
# in different models without touching the retrieval logic.
OPENAI_CHAT_MODEL: str = os.environ.get("OPENAI_CHAT_MODEL", "gpt-3.5-turbo")
OPENAI_EMBEDDING_MODEL: str = os.environ.get("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")

# The directory in which to persist the vector index.  Changing this will
# rebuild the index from scratch if the directory does not already exist.
PERSIST_DIR_NAME: str = ".vector_store"

# The maximum length of a snippet returned to the client.  Snippets are
# generated by truncating the chunk text at the nearest newline boundary.
SNIPPET_CHAR_LIMIT: int = 200

# Configure logging early.  Logs will be emitted to stdout.
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def _get_docs_dir() -> Path:
    """Resolve the documentation directory from the environment.

    Returns:
        Path: The absolute path to the documentation directory.

    Raises:
        SystemExit: If the directory does not exist or contains no Markdown files.
    """
    docs_dir = os.environ.get("DOCS_DIR", "./docs")
    docs_path = Path(docs_dir).resolve()
    if not docs_path.exists() or not docs_path.is_dir():
        logger.error("DOCS_DIR '%s' does not exist or is not a directory", docs_path)
        raise SystemExit(1)

    # Look for at least one Markdown file (.md or .mdx)
    md_files = list(docs_path.rglob("*.md")) + list(docs_path.rglob("*.mdx"))
    if not md_files:
        logger.error("DOCS_DIR '%s' contains no Markdown (.md/.mdx) files", docs_path)
        raise SystemExit(1)

    logger.info("Using documentation directory: %s", docs_path)
    return docs_path


def _build_or_load_index(docs_path: Path) -> VectorStoreIndex:
    """Build a vector index from the given docs or load it from disk.

    This function uses a persistent storage directory to avoid recomputation
    on subsequent runs.  If the persistence directory exists and contains
    data, the index is loaded.  Otherwise, a new index is built and saved.

    Args:
        docs_path (Path): The directory containing Markdown files.

    Returns:
        VectorStoreIndex: A LlamaIndex vector store built from the docs.
    """
    persist_dir = docs_path / PERSIST_DIR_NAME
    storage_context: Optional[StorageContext] = None

    if persist_dir.exists() and any(persist_dir.iterdir()):
        logger.info("Loading existing index from %s", persist_dir)
        storage_context = StorageContext.from_defaults(persist_dir=str(persist_dir))
        index = load_index_from_storage(storage_context)
        return index

    logger.info("Building new index; this may take a while...")

    # Collect documents from the docs directory.  Each Document carries
    # metadata about its file path relative to docs_path.  Only files with
    # extensions .md or .mdx are considered.
    documents: List[Document] = []
    for file_path in docs_path.rglob("*"):
        if file_path.suffix.lower() not in {".md", ".mdx"}:
            continue
        try:
            text = file_path.read_text(encoding="utf-8")
        except Exception as e:
            logger.warning("Skipping %s due to read error: %s", file_path, e)
            continue
        relative_path = str(file_path.relative_to(docs_path))
        documents.append(Document(text=text, metadata={"file_path": relative_path}))

    if not documents:
        logger.error("No readable Markdown files found under %s", docs_path)
        raise SystemExit(1)

    # Parse documents into nodes using the MarkdownNodeParser.  This splits
    # documents by heading and attaches a 'header_path' to the node metadata.
    parser = MarkdownNodeParser.from_defaults()
    nodes = parser.get_nodes_from_documents(documents)
    logger.info("Parsed %d nodes from %d documents", len(nodes), len(documents))

    # Prepare the embedding model and LLM.  The OpenAI credentials are
    # automatically picked up from the environment by the underlying
    # libraries.  You must set OPENAI_API_KEY and optionally OPENAI_API_BASE.
    embed_model = OpenAIEmbedding(model=OPENAI_EMBEDDING_MODEL)
    llm = OpenAI(model=OPENAI_CHAT_MODEL)
    service_context = ServiceContext.from_defaults(embed_model=embed_model, llm=llm)

    # Persist the index to disk.  The StorageContext handles writing
    # underlying data structures (such as the vector store and doc store) to
    # files under persist_dir.
    storage_context = StorageContext.from_defaults(persist_dir=str(persist_dir))
    index = VectorStoreIndex(nodes, storage_context=storage_context, service_context=service_context)
    storage_context.persist()
    logger.info("Index built and persisted at %s", persist_dir)
    return index


class DocsSearcher:
    """Encapsulates the vector index and provides search and QA methods."""

    def __init__(self, index: VectorStoreIndex) -> None:
        self._index = index

    def _format_result(self, node: Any, score: float) -> Dict[str, Union[str, float]]:
        """Convert a NodeWithScore into a result dictionary.

        Args:
            node: A TextNode or similar object containing content and metadata.
            score: The similarity score assigned by the retriever.

        Returns:
            Dict[str, Union[str, float]]: The formatted result.
        """
        metadata = node.metadata or {}
        file_path: str = metadata.get("file_path", "")
        header_path: str = metadata.get("header_path", "/")
        # Derive the most specific heading from the header_path.  The
        # header_path is formatted like "/Parent/Child/"; split and take
        # the last non‑empty segment.  If none exists, fall back to the file
        # name.
        heading: str = ""
        parts = [p for p in header_path.split("/") if p]
        if parts:
            heading = parts[-1]
        elif file_path:
            heading = Path(file_path).stem
        # Generate a short snippet by taking the beginning of the content.
        content: str = node.get_content()
        newline_pos = content.find("\n")
        snippet_end = newline_pos if 0 <= newline_pos < SNIPPET_CHAR_LIMIT else SNIPPET_CHAR_LIMIT
        snippet: str = content[:snippet_end].strip()
        return {
            "path": file_path,
            "heading": heading,
            "score": score,
            "snippet": snippet,
        }

    async def search(self, query: str, k: int = 6) -> List[Dict[str, Union[str, float]]]:
        """Perform a similarity search over the vector store.

        Args:
            query (str): The search query.
            k (int, optional): The maximum number of results to return. Defaults to 6.

        Returns:
            List[Dict[str, Union[str, float]]]: A list of search results.
        """
        logger.info("search_docs called with query='%s', k=%d", query, k)
        retriever = self._index.as_retriever(similarity_top_k=k)
        results = retriever.retrieve(query)
        formatted = [self._format_result(r.node, r.score) for r in results]
        return formatted

    async def ask(self, question: str) -> Dict[str, Any]:
        """Answer a natural‑language question using retrieval‑augmented generation.

        Args:
            question (str): The question to answer.

        Returns:
            Dict[str, Any]: An answer and citations.
        """
        logger.info("ask_docs called with question='%s'", question)
        query_engine = self._index.as_query_engine()
        response = query_engine.query(question)
        answer: str = str(response)
        citations: List[Dict[str, str]] = []
        for source_node in response.source_nodes:
            node = source_node.node
            metadata = node.metadata or {}
            file_path: str = metadata.get("file_path", "")
            header_path: str = metadata.get("header_path", "/")
            parts = [p for p in header_path.split("/") if p]
            heading: str = parts[-1] if parts else (Path(file_path).stem if file_path else "")
            content = node.get_content()
            newline_pos = content.find("\n")
            snippet_end = newline_pos if 0 <= newline_pos < SNIPPET_CHAR_LIMIT else SNIPPET_CHAR_LIMIT
            snippet = content[:snippet_end].strip()
            citations.append({"path": file_path, "heading": heading, "snippet": snippet})
        return {"answer": answer, "citations": citations}


def build_app() -> FastMCP:
    """Construct and return the FastMCP application.

    Returns:
        FastMCP: The configured MCP application exposing our tools.
    """
    docs_path = _get_docs_dir()
    index = _build_or_load_index(docs_path)
    searcher = DocsSearcher(index)

    app = FastMCP()

    @app.tool(
        name="search_docs",
        description="Search the local documentation with a text query. Returns a list of matching sections with path, heading, score, and snippet.",
    )
    async def search_docs(query: str, k: int = 6) -> List[Dict[str, Union[str, float]]]:
        """Search the indexed documentation.

        Args:
            query (str): The search query.
            k (int, optional): The number of results to return. Defaults to 6.

        Returns:
            List[dict]: A list of results with ``path``, ``heading``, ``score`` and ``snippet``.
        """
        return await searcher.search(query, k)

    @app.tool(
        name="ask_docs",
        description="Ask a question over the local documentation. Returns an answer with citations.",
    )
    async def ask_docs(question: str) -> Dict[str, Any]:
        """Answer a question using the indexed documentation.

        Args:
            question (str): The question to answer.

        Returns:
            dict: A dictionary with ``answer`` and ``citations``.
        """
        return await searcher.ask(question)

    return app


def main() -> None:
    """Entry point for running the MCP server.

    This function simply constructs the application and hands control to the
    FastMCP runner.  When run with the MCP CLI (e.g., ``uv run mcp dev server.py``),
    MCP will invoke this function automatically.  When run directly via
    ``python server.py``, this function starts the server as well.
    """
    app = build_app()
    # The FastMCP runner automatically reads the ASGI app and exposes the
    # tools defined above.  When this module is run as a script, call run()
    # directly.  When executed under ``mcp dev``, the CLI will call run()
    # implicitly.
    app.run()


if __name__ == "__main__":
    main()